name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: sccache

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Use Bun
        uses: oven-sh/setup-bun@v2

      - name: Install wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build Wasm
        run: |
          bun wasm

      - name: Build Plugin
        run: |
          bun install
          mv ./pkg/typst_wasm_bg.wasm ./typst.wasm
          bun run build

      - name: Show sccache stats
        run: sccache --show-stats

      - name: Create Release
        if: github.event_name != 'workflow_dispatch'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: |
          gh release create "$TAG" \
            dist/main.js \
            dist/styles.css \
            dist/manifest.json \
            dist/typst-${TAG}.wasm
